FROM dvcorg/cml-gpu:latest

LABEL maintainer="dvc.org"

RUN apt-get update && \
    apt-get install -y --no-install-recommends --fix-missing \
            python3 \
            python3-pip && \
    pip3 install --upgrade pip && \
    update-alternatives --install \
            /usr/bin/python python $(which python3) 10

