FROM dvcorg/dvc-cml-py3:latest

LABEL maintainer="dvc.org"

RUN apt-get remove -y dvc && \
    apt-get install -y --no-install-recommends --fix-missing \
        git \
        python3-setuptools \
        python3-dev && \
    git clone https://github.com/iterative/dvc/ && \
    cd dvc && \
    git checkout 128fa7f && \
    pip install -U -e .[all,tests] && \
    cd .. && \
    rm -rf dvc

