name: Test & Deploy
on: push
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v0.18.20
      - uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org
      - run: npm install
      - run: |
          VERSION=$(jq -r .version < package.json)
          npm install --dry-run @dvcorg/cml@$VERSION ||
          npm ${{ inputs.release && 'publish' || 'publish --dry-run' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Step required "thanks" to https://github.com/actions/runner-images/issues/6283
      - uses: Homebrew/actions/setup-homebrew@29b2973f18e5aca5443f4b3d87f68eda7a27b22b
      - run: brew install ldid
      - run: |
          cp node_modules/@npcz/magic/dist/magic.mgc assets/magic.mgc
          npx --yes pkg --no-bytecode --public-packages "*" --public package.json
          for cmd in '' runner publish pr; do build/cml-linux-x64 $cmd --version; done
          cp build/cml-linux{-x64,}
          cp build/cml-macos{-x64,}
      - run:
          find build -type f | xargs gh release upload
          v0.18.20
        env:
          GITHUB_TOKEN: ${{ github.token }}
